Why would I name docker-compose.prod instead of staying standard?

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,9 +40,14 @@ jobs:
       run: |
         ssh -i private_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
           cd /tmp/c218/ &&
-          docker-compose down &&
-          docker-compose up -d --build &&
-          docker image prune -f
+          if [ -f docker-compose.prod.yml ]; then
+            docker-compose -f docker-compose.prod.yml down &&
+            docker-compose -f docker-compose.prod.yml up -d --build &&
+            docker image prune -f
+          else
+            echo 'docker-compose.prod.yml not found'
+            exit 1
+          fi
         "
 
     - name: Clean up application files
